[build-system]
requires = [
  "setuptools==59.2.0", "wheel==0.37.0", "cmake==3.22.3", "pip",
  "scikit-build==0.13.1", 
  "numpy==1.11.3; python_version=='3.5'",
  "numpy==1.13.3; python_version=='3.6'",
  "numpy==1.14.5; python_version=='3.7'",
  "numpy==1.17.3; python_version>='3.8'"
]
